name: 'Common Node Setup'
description: 'Setup Node.js, cache npm, and install dependencies'
runs:
    using: 'composite'
    steps:
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
        - name: Cache npm
          uses: actions/cache@v4
          with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ inputs.node-version }}-npm-${{ hashFiles('react/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-node-${{ inputs.node-version }}-npm-
        - name: Install dependencies
          run: npm install
          shell: bash
          working-directory: react
inputs:
    node-version:
        description: 'Node.js version'
        required: true
        type: string
