#!/bin/sh
# Bandwidth Usage Setup
# AsusWRT-Merlin Version
#
# Cron Utility
# add:    cru a <unique id> <"min hour day month week command">
#		min (0 - 59)
#		hour (0 - 23)
#		day (1 - 31)
#		month (1 - 12)
#		week (0 - 6) (Sunday=0)
# delete: cru d <unique id>
# list:   cru l

BWDIR=/opt/share/bwmon
BWMON=${BWDIR}/bwmon.sh

start() {
	echo " Starting bwmon..."
	cru a bwmon_setup "* * * * * $BWMON setup $BWDIR"
	cru a bwmon_update "1,31 * * * * $BWMON update $BWDIR"
}

stop() {
	echo " Stopping bwmon..."
	cru d bwmon_update
	cru d bwmon_setup
}

check() {
	echo " Checking bwmon..."
	cru l | grep bwmon
}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	check)
		check
		;;
	*)
	echo "Usage: $0 {start|stop|check|restart}"
esac

exit 0 

