call npm.cmd install --save-dev grunt
call npm.cmd install --save-dev grunt-angular-templates
call npm.cmd install --save-dev grunt-contrib-concat
call npm.cmd install --save-dev grunt-contrib-cssmin
call npm.cmd install --save-dev grunt-contrib-jshint
call npm.cmd install --save-dev grunt-contrib-nodeunit
call npm.cmd install --save-dev grunt-protractor-runner
call npm.cmd install --save-dev grunt-contrib-uglify
call npm.cmd install --save-dev grunt-karma
call npm.cmd install --save-dev grunt-preprocess
call npm.cmd install --save-dev grunt-template
call npm.cmd install --save-dev karma
call npm.cmd install --save-dev karma-chrome-launcher
call npm.cmd install --save-dev karma-coffee-preprocessor
call npm.cmd install --save-dev karma-coverage
call npm.cmd install --save-dev karma-firefox-launcher
call npm.cmd install --save-dev karma-html2js-preprocessor
call npm.cmd install --save-dev karma-jasmine
call npm.cmd install --save-dev karma-junit-reporter
call npm.cmd install --save-dev karma-phantomjs-launcher
call npm.cmd install --save-dev karma-requirejs
call npm.cmd install --save-dev karma-script-launcher
call npm.cmd install --save-dev matchdep
call npm.cmd install --save-dev protractor
call npm.cmd install --save-dev requirejs
