call npm.cmd update grunt
call npm.cmd update grunt-angular-templates
call npm.cmd update grunt-contrib-concat
call npm.cmd update grunt-contrib-cssmin
call npm.cmd update grunt-contrib-jshint
call npm.cmd update grunt-contrib-nodeunit
call npm.cmd update grunt-protractor-runner
call npm.cmd update grunt-contrib-uglify
call npm.cmd update grunt-karma
call npm.cmd update grunt-preprocess
call npm.cmd update grunt-template
call npm.cmd update karma
call npm.cmd update karma-chrome-launcher
call npm.cmd update karma-coffee-preprocessor
call npm.cmd update karma-coverage
call npm.cmd update karma-firefox-launcher
call npm.cmd update karma-html2js-preprocessor
call npm.cmd update karma-jasmine
call npm.cmd update karma-junit-reporter
call npm.cmd update karma-phantomjs-launcher
call npm.cmd update karma-requirejs
call npm.cmd update karma-script-launcher
call npm.cmd update matchdep
call npm.cmd update protractor
call npm.cmd update requirejs
